In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import lightgbm as lgb
import eli5
from sklearn.feature_extraction.text import TfidfVectorizer
from bayes_opt import BayesianOptimization
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression

c:\Users\Administrator\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [29]:
# Let's explore the data we have here

train = pd.read_csv("./train.csv")
test = pd.read_csv("./test.csv")
stores = pd.read_csv("./stores.csv")
transactions = pd.read_csv("./transactions.csv")
h_days = pd.read_csv("./holidays_events.csv")
oil = pd.read_csv("./oil.csv")

In [30]:
train.head(5)

id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [31]:
def merge(df, m_df, on = 'date'):
 df = pd.merge(how = 'left', on = on, left = df, right = m_df)

 return df

train = merge(train, oil, "date")
train = merge(train, h_days)
train = merge(train, stores, "store_nbr")
train = merge(train, transactions, ["store_nbr", "date"])

test = merge(test, oil, "date")
test = merge(test, h_days)
test = merge(test, stores, "store_nbr")
test = merge(test, transactions, ["store_nbr", "date"])

train = train.drop(['store_nbr'], axis = 1)
test = test.drop(['store_nbr'], axis = 1)

In [32]:

'2012-03-02' in h_days['date'].unique()

True

In [33]:
check = pd.to_datetime(['2018-10-26 12:00 -0530', '2018-10-26 12:00 -0500'],
               utc=True)

def split_date(df):
 all_hdays = h_days['date'].unique()

 df['is_holiday'] = df['date'].apply(lambda x: 1 if x in all_hdays else 0)
 
 df['date'] = pd.to_datetime(df['date'])

 df['day'] = df['date'].apply(lambda x: x.day)
 df['month'] = df['date'].apply(lambda x: x.month)
 df['year'] = df['date'].apply(lambda x: x.year)
 df['quarter'] = df['date'].apply(lambda x: x.quarter)

 df = df.drop(['date'], axis = 1)

 return df

train = split_date(train)
test = split_date(test)

In [34]:
def encode(df):
 le = LabelEncoder()
 cols_to_encode = ["family", "state", "type_holiday", "type_store", "locale", "locale_name", "transferred", "city"]

 for c in cols_to_encode:
  df[c] = le.fit_transform(df[c])
 
 return df

train = encode(train)
test = encode(test)

In [35]:
train["is_holiday"].unique()

array([1, 0], dtype=int64)

In [36]:
train = train.drop(["type_store"], axis = 1)
test = test.drop(["type_store"], axis = 1)

In [37]:
# Fill the missing data:

train.isnull().sum()

id                    0
family                0
sales                 0
onpromotion           0
dcoilwtico       955152
type_holiday          0
locale                0
locale_name           0
description     2551824
transferred           0
city                  0
state                 0
cluster               0
transactions     249117
is_holiday            0
day                   0
month                 0
year                  0
quarter               0
dtype: int64

In [38]:
# Let's predict the missing values (for the oil column)

def predict_oil(df):

 first_copy = df.copy()
 first_copy = first_copy.drop(['description', "transactions"], axis = 1)

 oil_test_data = first_copy[first_copy["dcoilwtico"].isnull()]
 second_copy = first_copy.copy()
 second_copy.dropna(inplace=True)
 
 oil_y_train = second_copy["dcoilwtico"]
 oil_x_train = second_copy.drop(['dcoilwtico'], axis = 1)
 oil_x_test = oil_test_data.drop(['dcoilwtico'], axis = 1)

 print(oil_y_train.shape)
 print(oil_x_train.shape)
 model = LinearRegression()
 model.fit(oil_x_train, oil_y_train)

 oil_y_test = model.predict(oil_x_test)

 oil_y_test = np.round(oil_y_test, decimals = 0)

 print(oil_y_test)

 indices = df[df["dcoilwtico"].isnull()].index

 for fill_index, dataframe_index in enumerate(indices):
  df.loc[dataframe_index, "dcoilwtico"] = oil_y_test[fill_index]

 return df

train = predict_oil(train)
test = predict_oil(test)

(2099196,)
(2099196, 16)
[102. 102. 102. ...  31.  31.  31.]
(21384,)
(21384, 15)
[48. 48. 48. ... 47. 47. 47.]


In [39]:
train.isna().sum()

id                    0
family                0
sales                 0
onpromotion           0
dcoilwtico            0
type_holiday          0
locale                0
locale_name           0
description     2551824
transferred           0
city                  0
state                 0
cluster               0
transactions     249117
is_holiday            0
day                   0
month                 0
year                  0
quarter               0
dtype: int64

In [40]:
train.isna().sum()

id                    0
family                0
sales                 0
onpromotion           0
dcoilwtico            0
type_holiday          0
locale                0
locale_name           0
description     2551824
transferred           0
city                  0
state                 0
cluster               0
transactions     249117
is_holiday            0
day                   0
month                 0
year                  0
quarter               0
dtype: int64

In [41]:
# Let's predict the missing values (for the oil column)

def predict_transactions(df):

 first_copy = df.copy()
 first_copy = first_copy.drop(['description', "dcoilwtico"], axis=1)

 oil_test_data = first_copy[first_copy["transactions"].isnull()]
 second_copy = first_copy.copy()
 second_copy.dropna(inplace=True)

 oil_y_train = second_copy["transactions"]
 oil_x_train = second_copy.drop(['transactions'], axis=1)
 oil_x_test = oil_test_data.drop(['transactions'], axis=1)

 print(oil_y_train.shape)
 print(oil_x_train.shape)
 model = LinearRegression()
 model.fit(oil_x_train, oil_y_train)

 oil_y_test = model.predict(oil_x_test)

 oil_y_test = np.round(oil_y_test, decimals=0)

 print(oil_y_test)

 indices = df[df["transactions"].isnull()].index

 for fill_index, dataframe_index in enumerate(indices):
  df.loc[dataframe_index, "transactions"] = oil_y_test[fill_index]

 return df


train = predict_transactions(train)

(2805231,)
(2805231, 16)
[2140. 2142. 2145. ... 1736. 1738. 1740.]


In [46]:
train.isnull().sum()

id                        0
family                    0
sales                     0
onpromotion               0
dcoilwtico                0
type_holiday              0
locale                    0
locale_name               0
description         2551824
transferred               0
city                      0
state                     0
cluster                   0
transactions              0
is_holiday                0
day                       0
month                     0
year                      0
quarter                   0
oil_is_expensive          0
after_paycheck            0
dtype: int64

In [42]:
# Feature engineering

def f_eng(df):
 oil_mean_price = df['dcoilwtico'].describe()["mean"]
 df['after_paycheck'] = df['day'].apply(lambda x: 1 if (15 <= x <= 18) or (29 <= x <= 31) or (0 <= x <= 2) else 0)

 return df

train = f_eng(train)
test = f_eng(test)

In [52]:
# Find the words that have the most impact on the amount of sales

vectorizer = TfidfVectorizer(
 sublinear_tf = True,
 analyzer = "word",
 token_pattern = r"\w{1,}",
 ngram_range = (1,2),
 min_df = 5
)

description_text = vectorizer.fit_transform(train['description'].fillna(""))
model = LinearRegression()
model.fit(description_text, train["sales"])
eli5.show_weights(model, vec = vectorizer, top = 20, feature_filter = lambda x: x != '<BIAS>')

c:\Users\Administrator\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [43]:
train.corr().style.background_gradient("YlOrBr")


In [44]:
# Before training model let's optimize it's memory usage

def reduce_mem_usage(df):
  numerics = ["int8", "int16", "int32", "int64", "float16", "float32", "float64"]
  start_mem = df.memory_usage().sum() / 1024**2

  for col in df.columns:
    col_type = df[col].dtypes

    if col_type in numerics:
      c_min = df[col].min()
      c_max = df[col].max()

      if str(col_type)[:3] == "int":
        if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
         df[col] = df[col].astype(np.int8)
    
        elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
         df[col] = df[col].astype(np.int16)
    
        elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
         df[col] = df[col].astype(np.int32)
    
        elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
         df[col] = df[col].astype(np.int64) 

      else:
        if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
          df[col] = df[col].astype(np.float16)
    
        elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
          df[col] = df[col].astype(np.float32)
    
        elif c_min > np.finfo(np.float64).min and c_max < np.finfo(np.float64).max:
          df[col] = df[col].axtype(np.float64)
 
  end_mem = df.memory_usage().sum() / 1024**2
 
  print("Memory usage decreased to {:5.2f} Mb ({:.1f}% reduction)".format(end_mem, 100 * (start_mem - end_mem) / start_mem))

  return df

train = reduce_mem_usage(train)

Memory usage decreased to 133.99 Mb (68.9% reduction)


In [45]:
# Let's optimize our LGBM model using Bayesian Optimization

y = train['sales']
