In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import lightgbm as lgb
import eli5
from sklearn.feature_extraction.text import TfidfVectorizer
from bayes_opt import BayesianOptimization
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.linear_model import LinearRegression

c:\Users\Administrator\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [2]:
# Let's explore the data we have here

train = pd.read_csv("./train.csv")
test = pd.read_csv("./test.csv")
stores = pd.read_csv("./stores.csv")
transactions = pd.read_csv("./transactions.csv")
h_days = pd.read_csv("./holidays_events.csv")
oil = pd.read_csv("./oil.csv")

In [3]:
train.head(5)

id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [4]:
def merge(df, m_df, on = 'date'):
 df = pd.merge(how = 'left', on = on, left = df, right = m_df)

 return df

train = merge(train, oil, "date")
train = merge(train, h_days)
train = merge(train, stores, "store_nbr")
train = merge(train, transactions, ["store_nbr", "date"])

test = merge(test, oil, "date")
test = merge(test, h_days)
test = merge(test, stores, "store_nbr")
test = merge(test, transactions, ["store_nbr", "date"])

train = train.drop(['store_nbr'], axis = 1)
test = test.drop(['store_nbr'], axis = 1)

In [5]:

'2012-03-02' in h_days['date'].unique()

True

In [6]:
check = pd.to_datetime(['2018-10-26 12:00 -0530', '2018-10-26 12:00 -0500'],
               utc=True)

def split_date(df):
 all_hdays = h_days['date'].unique()

 df['is_holiday'] = df['date'].apply(lambda x: 1 if x in all_hdays else 0)
 
 df['date'] = pd.to_datetime(df['date'])

 df['day'] = df['date'].apply(lambda x: x.day)
 df['month'] = df['date'].apply(lambda x: x.month)
 df['year'] = df['date'].apply(lambda x: x.year)
 df['quarter'] = df['date'].apply(lambda x: x.quarter)

 df = df.drop(['date'], axis = 1)

 return df

train = split_date(train)
test = split_date(test)

In [7]:
def encode(df):
 le = LabelEncoder()
 cols_to_encode = ["family", "state", "type_holiday", "type_store", "locale", "locale_name", "transferred", "city"]

 for c in cols_to_encode:
  df[c] = le.fit_transform(df[c])
 
 return df

train = encode(train)
test = encode(test)

In [8]:
train["is_holiday"].unique()

array([1, 0], dtype=int64)

In [9]:
train = train.drop(["type_store"], axis = 1)
test = test.drop(["type_store"], axis = 1)

In [10]:
# Fill the missing data:

train.isnull().sum()

id                    0
family                0
sales                 0
onpromotion           0
dcoilwtico       955152
type_holiday          0
locale                0
locale_name           0
description     2551824
transferred           0
city                  0
state                 0
cluster               0
transactions     249117
is_holiday            0
day                   0
month                 0
year                  0
quarter               0
dtype: int64

In [11]:
# Let's predict the missing values (for the oil column)

def predict_oil(df):

 first_copy = df.copy()
 first_copy = first_copy.drop(['description', "transactions"], axis = 1)

 oil_test_data = first_copy[first_copy["dcoilwtico"].isnull()]
 second_copy = first_copy.copy()
 second_copy.dropna(inplace=True)
 
 oil_y_train = second_copy["dcoilwtico"]
 oil_x_train = second_copy.drop(['dcoilwtico'], axis = 1)
 oil_x_test = oil_test_data.drop(['dcoilwtico'], axis = 1)

 print(oil_y_train.shape)
 print(oil_x_train.shape)
 model = LinearRegression()
 model.fit(oil_x_train, oil_y_train)

 oil_y_test = model.predict(oil_x_test)

 oil_y_test = np.round(oil_y_test, decimals = 0)

 print(oil_y_test)

 indices = df[df["dcoilwtico"].isnull()].index

 for fill_index, dataframe_index in enumerate(indices):
  df.loc[dataframe_index, "dcoilwtico"] = oil_y_test[fill_index]

 return df

train = predict_oil(train)
test = predict_oil(test)

(2099196,)
(2099196, 16)
[102. 102. 102. ...  31.  31.  31.]
(21384,)
(21384, 15)
[48. 48. 48. ... 47. 47. 47.]


In [12]:
train.isna().sum()

id                    0
family                0
sales                 0
onpromotion           0
dcoilwtico            0
type_holiday          0
locale                0
locale_name           0
description     2551824
transferred           0
city                  0
state                 0
cluster               0
transactions     249117
is_holiday            0
day                   0
month                 0
year                  0
quarter               0
dtype: int64

In [13]:
train.isna().sum()

id                    0
family                0
sales                 0
onpromotion           0
dcoilwtico            0
type_holiday          0
locale                0
locale_name           0
description     2551824
transferred           0
city                  0
state                 0
cluster               0
transactions     249117
is_holiday            0
day                   0
month                 0
year                  0
quarter               0
dtype: int64

In [14]:
# Let's predict the missing values (for the oil column)

def predict_transactions(df):

 first_copy = df.copy()
 first_copy = first_copy.drop(['description', "dcoilwtico"], axis=1)

 oil_test_data = first_copy[first_copy["transactions"].isnull()]
 second_copy = first_copy.copy()
 second_copy.dropna(inplace=True)

 oil_y_train = second_copy["transactions"]
 oil_x_train = second_copy.drop(['transactions'], axis=1)
 oil_x_test = oil_test_data.drop(['transactions'], axis=1)

 print(oil_y_train.shape)
 print(oil_x_train.shape)
 model = LinearRegression()
 model.fit(oil_x_train, oil_y_train)

 oil_y_test = model.predict(oil_x_test)

 oil_y_test = np.round(oil_y_test, decimals=0)

 print(oil_y_test)

 indices = df[df["transactions"].isnull()].index

 for fill_index, dataframe_index in enumerate(indices):
  df.loc[dataframe_index, "transactions"] = oil_y_test[fill_index]

 return df


train = predict_transactions(train)

(2805231,)
(2805231, 16)
[2140. 2142. 2145. ... 1736. 1738. 1740.]


In [15]:
train = train.drop(['description'], axis = 1)
test = test.drop(['description'], axis = 1)

In [16]:
# Feature engineering

def f_eng(df):
 oil_mean_price = df['dcoilwtico'].describe()["mean"]
 df['after_paycheck'] = df['day'].apply(lambda x: 1 if (15 <= x <= 18) or (29 <= x <= 31) or (0 <= x <= 2) else 0)

 return df

train = f_eng(train)
test = f_eng(test)

In [17]:
train.corr().style.background_gradient("YlOrBr")


In [18]:
# Before training model let's optimize it's memory usage

def reduce_mem_usage(df):
  numerics = ["int8", "int16", "int32", "int64", "float16", "float32", "float64"]
  start_mem = df.memory_usage().sum() / 1024**2

  for col in df.columns:
    col_type = df[col].dtypes

    if col_type in numerics:
      c_min = df[col].min()
      c_max = df[col].max()

      if str(col_type)[:3] == "int":
        if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
         df[col] = df[col].astype(np.int8)
    
        elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
         df[col] = df[col].astype(np.int16)
    
        elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
         df[col] = df[col].astype(np.int32)
    
        elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
         df[col] = df[col].astype(np.int64) 

      else:
        if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
          df[col] = df[col].astype(np.float16)
    
        elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
          df[col] = df[col].astype(np.float32)
    
        elif c_min > np.finfo(np.float64).min and c_max < np.finfo(np.float64).max:
          df[col] = df[col].axtype(np.float64)
 
  end_mem = df.memory_usage().sum() / 1024**2
 
  print("Memory usage decreased to {:5.2f} Mb ({:.1f}% reduction)".format(end_mem, 100 * (start_mem - end_mem) / start_mem))

  return df

train = reduce_mem_usage(train)

Memory usage decreased to 107.78 Mb (72.0% reduction)


In [19]:
# Prepare datasets for the model training

y = train['sales'].round()
X = train.drop(['sales'], axis = 1)

In [20]:
y.shape

(3054348,)

In [21]:
def bayes_parameter_opt_lgb(X, y, init_round=15, opt_round=25, n_folds=3, random_seed=6, n_estimators=10000, output_process=False):
    # prepare data
    train_data = lgb.Dataset(data=X, label=y, free_raw_data=False)
    # parameters

    def lgb_eval(learning_rate, num_leaves, feature_fraction, bagging_fraction, max_depth, max_bin, min_data_in_leaf, min_sum_hessian_in_leaf, subsample):
        params = {'application': 'binary', 'metric': 'auc'}
        params['learning_rate'] = max(min(learning_rate, 1), 0)
        params["num_leaves"] = int(round(num_leaves))
        params['feature_fraction'] = max(min(feature_fraction, 1), 0)
        params['bagging_fraction'] = max(min(bagging_fraction, 1), 0)
        params['max_depth'] = int(round(max_depth))
        params['max_bin'] = int(round(max_depth))
        params['min_data_in_leaf'] = int(round(min_data_in_leaf))
        params['min_sum_hessian_in_leaf'] = min_sum_hessian_in_leaf
        params['subsample'] = max(min(subsample, 1), 0)

        cv_result = lgb.cv(params, train_data, nfold=n_folds, seed=random_seed,
                           stratified=True, verbose_eval=200, metrics=['auc'])
        return max(cv_result['auc-mean'])

    lgbBO = BayesianOptimization(lgb_eval, {'learning_rate': (0.01, 1.0),
                                            'num_leaves': (24, 80),
                                            'feature_fraction': (0.1, 0.9),
                                            'bagging_fraction': (0.8, 1),
                                            'max_depth': (5, 30),
                                            'max_bin': (20, 90),
                                            'min_data_in_leaf': (20, 80),
                                            'min_sum_hessian_in_leaf': (0, 100),
                                            'subsample': (0.01, 1.0)}, random_state=200)

    # n_iter: How many steps of bayesian optimization you want to perform. The more steps the more likely to find a good maximum you are.
    # init_points: How many steps of random exploration you want to perform. Random exploration can help by diversifying the exploration space.

    lgbBO.maximize(init_points=init_round, n_iter=opt_round)

    model_auc = []
    for model in range(len(lgbBO.res)):
        model_auc.append(lgbBO.res[model]['target'])

    # return best parameters
    return lgbBO.res[pd.Series(model_auc).idxmax()]['target'], lgbBO.res[pd.Series(model_auc).idxmax()]['params']


# opt_params = bayes_parameter_opt_lgb(
#     X, y, init_round=5, opt_round=10, n_folds=3, random_seed=6, n_estimators=10000)


In [22]:
# Print out optimized parameters

opt_params = {}

opt_params["bagging_fraction"] = 0.820
opt_params['feature_fraction'] = 0.854
opt_params["learning_rate"] = 0.83
opt_params["max_depth"] = 27
opt_params["max_bin"] = 56
opt_params["min_data_in_leaf"] = 55
opt_params['min_sum_hessian_in_leaf'] = 45
opt_params['num_leaves'] = 62
opt_params['subsample'] = 0.425
opt_params["objective"] = 'binary'
opt_params['metric'] = 'auc'
opt_params['is_unbalance'] = True
opt_params["boost_from_average"] = False
opt_params

# b_frac: 0.820
# f_frac: 0.854
# rate: 0.83
# max_bin: 56
# max_depth 27
# min_data_in_leaf: 55
# min_sum_hessian_in_leaf: 45
# num_leaves: 62
# subsample: 0.425

{'bagging_fraction': 0.82,
 'feature_fraction': 0.854,
 'learning_rate': 0.83,
 'max_depth': 27,
 'max_bin': 56,
 'min_data_in_leaf': 55,
 'min_sum_hessian_in_leaf': 45,
 'num_leaves': 62,
 'subsample': 0.425,
 'objective': 'binary',
 'metric': 'auc',
 'is_unbalance': True,
 'boost_from_average': False}

In [23]:
# Train the model with the optimized parameters

target = train['sales'].round()
features = [c for c in train.columns if c not in ['sales', 'id']]


folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=31416)
oof = np.zeros(len(train))
predictions = np.zeros(len(test))
feature_importance_df = pd.DataFrame()

for fold_, (trn_idx, val_idx) in enumerate(folds.split(train.values, target.values)):
    print("Fold {}".format(fold_))
    trn_data = lgb.Dataset(
        train.iloc[trn_idx][features], label=target.iloc[trn_idx])
    val_data = lgb.Dataset(
        train.iloc[val_idx][features], label=target.iloc[val_idx])

    num_round = 15000
    clf = lgb.train(opt_params, trn_data, num_round, valid_sets=[
                    trn_data, val_data], verbose_eval=500, early_stopping_rounds=250)
    oof[val_idx] = np.argmax(clf.predict(
        train.iloc[val_idx][features], num_iteration=clf.best_iteration), axis = 0)

    fold_importance_df = pd.DataFrame()
    fold_importance_df["Feature"] = features
    fold_importance_df["importance"] = clf.feature_importance()
    fold_importance_df["fold"] = fold_ + 1
    feature_importance_df = pd.concat(
        [feature_importance_df, fold_importance_df], axis=0)

    predictions += clf.predict(test[features],
                               num_iteration=clf.best_iteration) / folds.n_splits




c:\Users\Administrator\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


Fold 0
[LightGBM] [Warning] bagging_fraction is set=0.82, subsample=0.425 will be ignored. Current value: bagging_fraction=0.82
[LightGBM] [Warning] bagging_fraction is set=0.82, subsample=0.425 will be ignored. Current value: bagging_fraction=0.82
[LightGBM] [Info] Number of positive: 1890493, number of negative: 858420
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.214999 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 356
[LightGBM] [Info] Number of data points in the train set: 2748913, number of used features: 17
[LightGBM] [Warning] bagging_fraction is set=0.82, subsample=0.425 will be ignored. Current value: bagging_fraction=0.82
Training until validation scores don't improve for 250 rounds
[500]	training's auc: 0.994358	valid_1's auc: 0.991546
Early stopping, best iteration is:
[583]	training's auc: 0.994683	valid_1's auc: 0

In [24]:
from sklearn.metrics import f1_score

print("CV score: {:<8.5f}".format(f1_score(target, oof, average = 'weighted')))


CV score: 0.00000 


In [25]:
target.shape

(3054348,)

In [26]:
train.columns

Index(['id', 'family', 'sales', 'onpromotion', 'dcoilwtico', 'type_holiday',
       'locale', 'locale_name', 'transferred', 'city', 'state', 'cluster',
       'transactions', 'is_holiday', 'day', 'month', 'year', 'quarter',
       'after_paycheck'],
      dtype='object')